<?
$redirect=$_REQUEST['redirect'];
$confirm=$_REQUEST['confirm'];
$redirect_str="";
if(isset($_REQUEST['search'])){
$redirect_str.="?search=".$_REQUEST['search'];
}
if(isset($_REQUEST['year'])){
$redirect_str.="&amp;year=".$_REQUEST['year'];
}
if(isset($_REQUEST['month'])){
$redirect_str.="&amp;month=".$_REQUEST['month'];
}
if(isset($_REQUEST['date'])){
$redirect_str.="&amp;date=".$_REQUEST['date'];
}
if(isset($_REQUEST['date_range1'])){
$redirect_str.="&amp;date_range1=".$_REQUEST['date_range1'];
}
if(isset($_REQUEST['date_range2'])){
$redirect_str.="&amp;date_range2=".$_REQUEST['date_range2'];
}
if(isset($_REQUEST['sort'])){
$redirect_str.="&amp;sort=".$_REQUEST['sort'];
}
if(isset($_REQUEST['pageset'])){
$redirect_str.="&amp;pageset=".$_REQUEST['pageset'];
}
$confirm_redirect=$redirect.$redirect_str;
?>